plugins = []
headers = []
redirects = []

[functions]

[functions."*"]

[build]
publish = "/Users/ij/.gemini/antigravity/scratch/nutri-buddy-app-26/dist/client"
publishOrigin = "ui"
commandOrigin = "ui"
command = "npm run build"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]