/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/app'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppIndexRouteImport } from './routes/app/index'
import { Route as AppFoodsRouteImport } from './routes/app/foods'
import { Route as AppOrientationsRouteImport } from './routes/app/orientations'
import { Route as AppPatientsRouteImport } from './routes/app/patients'
import { Route as AppPatientsIdRouteImport } from './routes/app/patients/$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppFoodsRoute = AppFoodsRouteImport.update({
  id: '/foods',
  path: '/foods',
  getParentRoute: () => AppRoute,
} as any)
const AppOrientationsRoute = AppOrientationsRouteImport.update({
  id: '/orientations',
  path: '/orientations',
  getParentRoute: () => AppRoute,
} as any)
const AppPatientsRoute = AppPatientsRouteImport.update({
  id: '/patients',
  path: '/patients',
  getParentRoute: () => AppRoute,
} as any)
const AppPatientsIdRoute = AppPatientsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppPatientsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/app/foods': typeof AppFoodsRoute
  '/app/orientations': typeof AppOrientationsRoute
  '/app/patients': typeof AppPatientsRouteWithChildren
  '/app/': typeof AppIndexRoute
  '/app/patients/$id': typeof AppPatientsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/app/foods': typeof AppFoodsRoute
  '/app/orientations': typeof AppOrientationsRoute
  '/app/patients': typeof AppPatientsRouteWithChildren
  '/app': typeof AppIndexRoute
  '/app/patients/$id': typeof AppPatientsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/app/foods': typeof AppFoodsRoute
  '/app/orientations': typeof AppOrientationsRoute
  '/app/patients': typeof AppPatientsRouteWithChildren
  '/app/': typeof AppIndexRoute
  '/app/patients/$id': typeof AppPatientsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/auth'
    | '/app/foods'
    | '/app/orientations'
    | '/app/patients'
    | '/app/'
    | '/app/patients/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/app/foods'
    | '/app/orientations'
    | '/app/patients'
    | '/app'
    | '/app/patients/$id'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/auth'
    | '/app/foods'
    | '/app/orientations'
    | '/app/patients'
    | '/app/'
    | '/app/patients/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/foods': {
      id: '/app/foods'
      path: '/foods'
      fullPath: '/app/foods'
      preLoaderRoute: typeof AppFoodsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/orientations': {
      id: '/app/orientations'
      path: '/orientations'
      fullPath: '/app/orientations'
      preLoaderRoute: typeof AppOrientationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/patients': {
      id: '/app/patients'
      path: '/patients'
      fullPath: '/app/patients'
      preLoaderRoute: typeof AppPatientsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/patients/$id': {
      id: '/app/patients/$id'
      path: '/$id'
      fullPath: '/app/patients/$id'
      preLoaderRoute: typeof AppPatientsIdRouteImport
      parentRoute: typeof AppPatientsRoute
    }
  }
}

interface AppPatientsRouteChildren {
  AppPatientsIdRoute: typeof AppPatientsIdRoute
}

const AppPatientsRouteChildren: AppPatientsRouteChildren = {
  AppPatientsIdRoute: AppPatientsIdRoute,
}

const AppPatientsRouteWithChildren = AppPatientsRoute._addFileChildren(
  AppPatientsRouteChildren,
)

interface AppRouteChildren {
  AppFoodsRoute: typeof AppFoodsRoute
  AppOrientationsRoute: typeof AppOrientationsRoute
  AppPatientsRoute: typeof AppPatientsRouteWithChildren
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppFoodsRoute: AppFoodsRoute,
  AppOrientationsRoute: AppOrientationsRoute,
  AppPatientsRoute: AppPatientsRouteWithChildren,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
